apiVersion: apps/v1
kind: Deployment
metadata:
  name: sumanth13ee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sumanth13ee 
  template:
    metadata:
      labels:
        app: sumanth13ee 
    spec:
      containers:
        - name: flask-app-es
          image: sumanth1204/student1227:latest
          ports:
            - containerPort: 5000
